### ISSUE TITLE
Upgrade to Asp.Net core 6.0

### ISSUE THREAD

**Issue by soernt** [yetanotherchris/Marten.AspNetIdentity#3]
I would like to use this package within a Core 6.0 project.
Are there any plans to update this package?

If not, do you accept pull requests?

**Comment by nkosi23** [comment]
For future people, while i agree that it would be cool if the package was still maintained, keep in mind that it is only composed of 2 main classes and overall 3-4 small files, so really do not hesitate to just copy and paste them into your project, quite easy to do.

**Comment by nkosi23** [comment]
What's more annoying however is that there is no license :laughing:

**Comment by yetanotherchris** [comment]
I'm currently migrating this to NET8 but it'll take slightly longer than a csproj file change, as I need to migrate away from Travis CI to GHA.

**Comment by filipbekic01** [comment]
This is very neat library, would be fantastic to keep it as updated as possible. Getting rid of other document dbs and use pgsql only is awesome!

**Comment by yetanotherchris** [comment]
It's .NET 8 now and uses Github Actions. I've also moved it as the Roadkill project is frozen and isn't being maintained.
